App/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
]

AuthorApp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.AuthorList.as_view()),
    path('<slug:slug>/', views.AuthorView.as_view()),
]

BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from Auth import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('AuthorApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', v.register),
    path('', include('App.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = ((0, "DRAFT"), (1, "PUBLISHED"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='images/', default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

AuthorApp/models.py
from django.db import models

# Create your models here.
STATUS = ((0, "DEAD"), (1, "ALIVE"))


class Author(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.IntegerField(choices=STATUS, default=1)
    content = models.TextField()
    author_image = models.ImageField(upload_to='Author/', default=0)

    def __str__(self):
        return self.name

App/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic


# Create your views here.
class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'


class DetailView(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

AuthorApp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Author


# Create your views here.


class AuthorList(generic.ListView):
    queryset = Author.objects.filter(status=1).order_by('-name')
    template_name = 'authors.html'


class AuthorView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'

templates/author_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ author.name }} {% endblock title %}</h1>
        <img src="{{ author.author_image.url }}" class="img-responsive" style="width: 300px" />
        <h3 class="card-text ">{{ author.content | safe }}</h3>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>
{% endblock content %}

templates/authors.html
{% extends "base.html" %}
{% block content %}
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class=" site-heading my-4 mt-3 text-black">DJANGO BOOK BLOG</h3>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <!-- Blog -->
    <div class="col-md-8 mt-3 left">
      {% for author in author_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ author.name }}</h2>
          <img src="{{ author.author_image.url }}" class="img-responsive" style="width: 150px" />
          <p class="card-text">{{author.content|slice:":400"}}</p>
          <a href="/authors/{{ author.slug }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% block sidebar %}
    {% include 'sidebar.html' %}
    {% endblock sidebar %}
  </div>
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>Book Blog App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!-- Bootstrap -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/journal/bootstrap.min.css"> -->
{#  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/flatly/bootstrap.min.css">#}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css">
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BOOK BLOG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/authors">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/login">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  {% block content %}
  <!-- Content -->
  {% endblock content %}
  <!-- Footer -->
  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; 2021 MohammadAmin Ghorbannezhad</p>
  </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class=" site-heading my-4 mt-3 text-black">DJANGO BOOK BLOG</h3>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <!-- Blog -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ post.title }}</h2>
          <img src="{{ post.image.url }}" class="img-responsive" style="width: 150px" />
          <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
          <p class="card-text">{{post.content|slice:":400"}}</p>
          <a href="{% url 'detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% block sidebar %}
    {% include 'sidebar.html' %}
    {% endblock sidebar %}
  </div>
</div>
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <img src="{{ post.image.url }}" class="img-responsive" style="width: 350px" />
        <h3 class=" text-muted">{{ post.author }} | {{ post.created_on }}</h3>
        <h4 class="card-text ">{{ object.content | safe }}</h4>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>
{% endblock content %}

templates/sidebar.html
{% block sidebar %}

<style>
  .card {
    box-shadow: 0 16px 48px #6a6a6b;
  }
</style>

<!-- Sidebar -->
<div class="col-md-4 float-right ">
  <div class="card my-4">
    <h5 class="card-header">About</h5>
    <div class="card-body">
      <p class="card-text"> This book blog app is created using django </p>
      <a href="https://github.com" class="btn btn-danger">Github link!</a>
      <a href="https://t.me/mg10l" class="btn btn-secondary">Telegram</a>
    </div>
  </div>
</div>

{% endblock sidebar %}